### ISSUE TITLE
Traceback (most recent call last): Error

### ISSUE THREAD

**Issue by Ryannessence** [smokejohn/bl_apply_mods_shapekey#3] opened 2022-01-05 12:15 UTC
Hello! I am getting this error with Blender 2.83, Blender 2.91 and Blender 2.92 and I fail to understand what I could be doing wrong.

Traceback (most recent call last):
File"C:\Users\Ryannessence\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SKkeeper-master\__init__.py", line 235, in execute receiver.data.shape_keys.key_blocks[i].name = sk_names[i]
AttributeError: 'NoneType' object has no attribute 'key_blocks'

location: <unknown location:-1

I have a high poly mesh with shape keys (350 shapekeys) and I was hoping to use the Decimate modifier to keep the shapekeys and have a low poly version of it. The addon only makes a copy of the first shapekey and then displays this error.

Here is what I have tried. I tried different blender versions, I tried to remove the armature modifier keeping only the decimate modifier. I also made it the top modifier. I tried removing some shapekeys. I also tried the three options you have in the addon and they all led me to that error. Any ideas?

**Comment by InfernoDigital** [comment] 2022-05-16 09:18
![image](https://user-images.githubusercontent.com/12396056/168560618-21beece0-9336-4701-a621-3247a3d916fb.png)
getting a similar error

**Comment by smokejohn** [comment] 2022-05-16 13:28
I need a example file to reproduce the error to be able to fix it. If you can supply one i might be able to take a look. Just attach it to a comment, please supply:
- file with setup that fails (simple as possible)
- Version of SKKeeper you used
 

I also have to say, that i can't alot as much time as i used to to this project, but i will try to fix the open issues with an update.

**Comment by JWBWork** [comment] 2022-05-21 14:22
Also having this issue

Unable to provide a simple sample, but I have some more logs if it's of any use - currently using skkeeper v1.6

```python
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.ops.object.modifier_apply(modifier="Mirror")
bpy.ops.object.modifier_apply(modifier="Subdivision")
bpy.ops.object.modifier_apply(modifier="Triangulate")
bpy.ops.object.modifier_apply(modifier="Mirror")
bpy.ops.object.modifier_apply(modifier="Subdivision")
bpy.ops.object.modifier_apply(modifier="Triangulate")
bpy.ops.sk.apply_mods_choice_sk(resource_list=[{"name":"Mirror", "selected":True}, {"name":"Subdivision", "selected":True}, {"name":"Triangulate", "selected":True}, {"name":"Armature", "selected":False}])
Python: Traceback (most recent call last):
  File "C:\Users\Jacob\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\SKkeeper\__init__.py", line 433, in execute
    receiver.data.shape_keys.key_blocks[i].name = sk_names[i]
AttributeError: 'NoneType' object has no attribute 'key_blocks'

location: <unknown location>:-1
```

**Comment by JWBWork** [comment] 2022-05-22 16:40
so I'm digging around the code and in the `execute` function I wrapped the offending line in a try-except and logged these exceptions without raising it
```python
            # restore the shapekey name
            try:
                receiver.data.shape_keys.key_blocks[i].name = sk_names[i]
            except Exception as e:
                print("Warning! receiver.data.shape_keys {}".format(e))
```
Running the function like this doesn't result in any further failures, and the shape keys seem to be applied correctly afterwords - they're just missing their proper names
![image](https://user-images.githubusercontent.com/25304054/169705089-372e5d59-d4cb-4002-aedb-0bee2ad987ba.png)
Here are the resulting logs:
```
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("sk_receiver") at 0x000001FC5E508F08>
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("sk_receiver") at 0x000001FC5E508F08>
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("sk_receiver") at 0x000001FC5E508F08>
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC5E846B08>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC5E846B08>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC5E846B08>
Warning: Selected meshes must have equal numbers of vertices
Warning! receiver.data.shape_keys 'NoneType' object has no attribute 'key_blocks'
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC672E9608>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC672E9608>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC672E9608>
Warning! receiver.data.shape_keys bpy_prop_collection[index]: index 2 out of range, size 2
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
Warning! receiver.data.shape_keys bpy_prop_collection[index]: index 3 out of range, size 3
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
Warning! receiver.data.shape_keys bpy_prop_collection[index]: index 4 out of range, size 4
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
Warning! receiver.data.shape_keys bpy_prop_collection[index]: index 5 out of range, size 5
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
Warning! receiver.data.shape_keys bpy_prop_collection[index]: index 6 out of range, size 6
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F5608>
Warning! receiver.data.shape_keys bpy_prop_collection[index]: index 7 out of range, size 7
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC672E9608>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC672E9608>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC672E9608>
Warning! receiver.data.shape_keys bpy_prop_collection[index]: index 8 out of range, size 8
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F6408>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F6408>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F6408>
Warning! receiver.data.shape_keys bpy_prop_collection[index]: index 9 out of range, size 9
<SKkeeper 12:12> Mirror
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F6408>
<SKkeeper 12:12> Subdivision
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F6408>
<SKkeeper 12:12> Triangulate
<SKkeeper 12:12> Applying chosen modifier
<SKkeeper 12:12> <bpy_struct, Object("Body_shapekey_1") at 0x000001FC177F6408>
Warning! receiver.data.shape_keys bpy_prop_collection[index]: index 10 out of range, size 10
```

**Comment by JWBWork** [comment] 2022-05-22 16:42
Looks like changing the offending line to this seems to have fixed it for me
```python
receiver.data.shape_keys.key_blocks[i-1].name = sk_names[i]
```
assuming this is some mismatch between one being 0 indexes and the other starting at 1? Not sure why it worked before this fix and not after - I think it has something to do with editing the mesh or shape keys after creating several shape keys

* Correction: looks like this can result in mismatched names/blend shapes 😅

**Comment by TarkanV** [comment] 2022-08-01 14:46
> ![image](https://user-images.githubusercontent.com/12396056/168560618-21beece0-9336-4701-a621-3247a3d916fb.png) getting a similar error

By the way, for anyone having an "index out range error", I have a solution :v
 The problem is that you probably don't have the same number of vertices between your shape keys due to mirror modifier merging vertices at the center. So check if there's any center vertex that's not properly positioned according to your mirror modifier and retry :v
 Probably need to catch that in the code and add a warning for the possibility of that issue.

**Comment by sanyi12** [comment] 2023-02-10 14:26
omg that worked!!! @smokejohn should definitely put that in the description - when apply mirror modifier always uncheck the merge (because of possible vertices that will mess up the final mesh)
thousand thanks to @TarkanV

**Comment by TarkanV** [comment] 2023-02-10 14:49
> omg that worked!!! @smokejohn should definitely put that in the description - when apply mirror modifier always uncheck the merge (because of possible vertices that will mess up the final mesh) thousand thanks to @TarkanV

Lol no problem. Another solution, if you want to keep your vertices merged, is to just check if any of the shape keys are not properly positioned on the mirror axis ( for example their x position is not equal 0) to be able to merge in the first place, so positioning them back to 0 so they can merge as they should fixes the problem too.

**Comment by GunGryphon** [comment] 2024-09-09 06:33
Sorry to tag onto an old post, but I'm also running into the same errors listed above. 
I'm not using any mirror modifiers, but I am running two solidify mods and doing a weld to merge the edges after the fact. I'm using this particular stack to offset the UV's generated by the solidify modifier (to reduce bake issues in Substance). 
Before:
![image](https://github.com/user-attachments/assets/c4537f36-c358-4ddc-af24-2f488a215b3c)
After:
![image](https://github.com/user-attachments/assets/bf1cb53f-dba2-4b75-b472-c3fc91606843)

I get a slightly different error when applying to another object with the same modifier stack:
![image](https://github.com/user-attachments/assets/54404920-3349-4000-b980-f99ab6a706d4)

![image](https://github.com/user-attachments/assets/f3c4c898-3d12-4f22-a98b-1582c326ad66)

The error only occurs when applying the weld modifier. I could do forgo all of this by doing everything manually, but that defeats the intent of developing a non-destructive workflow. Is there a way we could get information on which are the offending vertices so they can be adjusted? 
Thanks for your time.

**Comment by smokejohn** [comment] 2024-12-23 18:41
duplicate of #10

**Closed as not planned by smokejohn** 2024-12-23 18:41 UTC
Labels: bug, documentation
