### ISSUE TITLE
New shapekeys are not animated

### ISSUE THREAD

**Issue by methusalah** [smokejohn/bl_apply_mods_shapekey#4] opened 2022-06-10 09:24 UTC
I tried the plugin in a scene where shapekeys values are changed during the animation. After applying modifiers, the shapekeys are still there with the correct names, but they are not animated anymore.

My best guess is that the shapekeys present after the plugin applies are new ones, and the original shapekeys used in the keyframes are gone.

Would it be possible for the plugin to preserve animations? Or maybe it is possible to solve that issue another way?

**Comment by methusalah** [comment] 2022-06-10 13:43
I realized that the faulty shape keys were in fact using a driver. So the problem is that SKKeeper does not reproduce the drivers of the shape keys I suppose.

**Comment by smokejohn** [comment] 2022-06-13 09:56
duplicate of #2

**Closed as not planned by smokejohn** 2022-06-13 09:56 UTC
Labels: enhancement
